controller_list:
  - name: dynamixel/right_arm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - right_shoulder_1_joint
      - right_shoulder_2_joint
      - right_elbow_joint
      - right_wrist_1_joint
      - right_wrist_2_joint
      - right_wrist_3_joint
  - name: dynamixel/left_arm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - left_shoulder_1_joint
      - left_shoulder_2_joint
      - left_elbow_joint
      - left_wrist_1_joint
      - left_wrist_2_joint
      - left_wrist_3_joint
  - name: dynamixel/right_gripper_controller
    action_ns: gripper_action
    type: GripperCommand
    default: true
    joints:
      - right_gripper_joint
  - name: dynamixel/left_gripper_controller
    action_ns: gripper_action
    type: GripperCommand
    default: true
    joints:
      - left_gripper_joint
